name: "易班打卡"
on:
  workflow_dispatch:
  schedule:
    - cron: "30 1 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: pip install
      run: |
        pip install -r requirements.txt
    - name: 签到
      run: |
        python yiban.py
